// Données du portfolio — Arkam ALI
// Contenu FR / EN centralisé ici. Pas de téléphone (volontairement).

export const personal = {
  name: "Arkam ALI",
  initials: "AA",
  email: "arkam.ali_pro@outlook.com",
  github: "https://github.com/abdoulkarim23",
  linkedin: "https://www.linkedin.com/in/abdoulkarim-ali-25825b212",
  planquia: "https://planquia.com",
  company: {
    name: "Conjectura",
    url: "https://conjectura.fr",
    product: "Planquia",
  },
};

const skillsShared = {
  genai: [
    "RAG",
    "multilingual-e5-large",
    "FAISS",
    "BM25",
    "RRF",
    "BGE-Reranker",
    "Prompt engineering",
    "LangChain",
    "Mistral",
    "BERT",
    "OpenAI & Anthropic",
  ],
  ml: [
    "Python",
    "SQL",
    "Java",
    "PyTorch",
    "TensorFlow",
    "scikit-learn",
    "Transformers",
    "Hugging Face",
  ],
};

export const copy = {
  fr: {
    ui: {
      documentTitle: "Arkam ALI — Ingénieur IA/ML | GenAI, RAG, On-premise",
      contactMe: "Me contacter",
      seeProjects: "Voir les projets",
      openMenu: "Ouvrir le menu",
      closeMenu: "Fermer le menu",
      allRepos: "Tous les repos",
      flagship: "Flagship",
      confidential: "Confidentiel",
      current: "En cours",
      openProject: "Ouvrir",
      visitPlanquia: "Visiter planquia.com",
      navLabel: "NAVIGATION",
      elsewhere: "AILLEURS",
      rights: "Tous droits réservés.",
      crafted: "Conçu & développé avec rigueur • Paris",
      langSwitch: "Langue",
    },
    navLinks: [
      { href: "#about", label: "À propos" },
      { href: "#experience", label: "Expérience" },
      { href: "#projects", label: "Projets" },
      { href: "#skills", label: "Compétences" },
      { href: "#education", label: "Formation" },
      { href: "#planquia", label: "Planquia" },
      { href: "#contact", label: "Contact" },
    ],
    personal: {
      title: "Ingénieur IA/ML — Production GenAI",
      tagline:
        "Je conçois et déploie des systèmes GenAI de production — RAG, recherche sémantique et serving de LLMs — y compris on-premise et air-gapped, sans dépendance cloud.",
      location: "Paris, France",
      status: "Stage HENSOLDT (Allemagne) • GenAI on-premise",
      companyRole: "Co-fondateur & CTO",
      chips: [
        "Production GenAI",
        "RAG hybride",
        "On-premise / air-gapped",
        "vLLM · FAISS",
      ],
      footerBlurb:
        "Ingénieur IA/ML — GenAI de production, RAG et déploiement on-premise. Basé à Paris.",
    },
    about: {
      eyebrow: "// 01 — Profil",
      heading: "Des systèmes GenAI qui tiennent en production",
      paragraphs: [
        "Ingénieur IA/ML, je construis des systèmes GenAI de production — RAG, recherche sémantique et serving de LLMs — avec une ownership de bout en bout : préparation des données, modélisation, évaluation et optimisation de latence.",
        "Mon terrain de jeu distinctif : le déploiement on-premise et air-gapped, sans dépendance cloud. J'ai conçu et industrialisé ces stacks en environnement défense — chez HENSOLDT (Allemagne) et à l'État-major des armées (CIMD) — sur infrastructure contrainte (vLLM, FAISS, NVIDIA DGX).",
        "En parallèle, je suis co-fondateur & CTO de Conjectura. J'y développe Planquia, un SaaS qui transforme des plans PDF de construction en devis structurés via un pipeline multimodal (OCR, vision, raisonnement LLM).",
      ],
      highlights: [
        { label: "Hit@1 NCORE AI", value: "+12 pts" },
        { label: "Latence / document", value: "~22s" },
        { label: "Déploiement", value: "Air-gapped" },
        { label: "Langues parlées", value: "4" },
      ],
    },
    experience: {
      eyebrow: "// 02 — Parcours",
      heading: "Expérience professionnelle",
      items: [
        {
          id: "exp-hensoldt",
          role: "Software Engineer — AI",
          kind: "Stage international",
          company: "HENSOLDT",
          period: "Juin — Sept. 2026",
          location: "Fürstenfeldbruck, Allemagne",
          current: true,
          description:
            "Conception et déploiement de NCORE AI, un système RAG de bout en bout pour l'identification des codes NATO Item Name à partir de PDFs techniques — en environnement air-gapped, sans cloud.",
          achievements: [
            "Déploiement sur NVIDIA DGX Spark avec vLLM, optimisé pour une infrastructure contrainte (GPU / unified memory, CPU offloading, quantization NVFP4).",
            "Pipeline de retrieval hybride : FAISS + BM25 + Reciprocal Rank Fusion, reranking cross-encoder BGE, génération Mistral-Small-4.",
            "Ingestion PDF multimodale (vision) et garde-fou de traduction pour un corpus technique multilingual.",
            "Harness d'évaluation : Hit@1 porté de 19 % à 31 %, latence ramenée à ~22 s par document.",
          ],
          stack: [
            "vLLM",
            "FAISS",
            "BM25",
            "RRF",
            "BGE-Reranker",
            "Mistral-Small-4",
            "NVIDIA DGX",
            "Python",
          ],
        },
        {
          id: "exp-cimd",
          role: "Data Scientist / AI Engineer",
          kind: "Alternance",
          company: "État-major des armées — CIMD",
          period: "Sept. 2024 — Août 2026",
          location: "Paris",
          current: false,
          description:
            "Mise en production d'un moteur de recherche sémantique et d'un assistant IA pour la codification NATO, en environnement on-premise sécurisé.",
          achievements: [
            "Moteur de recherche sémantique (RAG) pour la codification NATO, embeddings multilingual-e5-large et indexation vectorielle FAISS.",
            "Assistant IA (Mistral + RAG) pour interroger les règles NATO, avec injection de contexte maîtrisée.",
            "Interfaces opérationnelles CLI + Streamlit pour un usage métier quotidien.",
            "Tableaux de bord et KPIs sous QlikSense, dans un SI on-premise contraint.",
          ],
          stack: [
            "Python",
            "RAG",
            "FAISS",
            "Mistral",
            "multilingual-e5-large",
            "Streamlit",
            "QlikSense",
          ],
        },
        {
          id: "exp-conjectura",
          role: "Co-fondateur & CTO",
          kind: "Entrepreneuriat",
          company: "Conjectura — Planquia",
          period: "2026 — Présent",
          location: "Paris",
          current: true,
          description:
            "Lead developer de Planquia, un SaaS IA qui convertit des plans PDF de construction en devis structurés. Architecture, backend et roadmap produit.",
          achievements: [
            "Pipeline IA multimodal : OCR, computer vision et raisonnement LLM pour extraire et structurer l'information des plans.",
            "Stack full-stack : Python, FastAPI, SQLAlchemy, React / Next.js, PostgreSQL.",
            "Ownership produit : architecture, API, qualité de code et priorisation de la roadmap.",
          ],
          stack: [
            "Python",
            "FastAPI",
            "SQLAlchemy",
            "Next.js",
            "PostgreSQL",
            "OCR",
            "LLM",
          ],
        },
      ],
    },
    projects: {
      eyebrow: "// 03 — Réalisations",
      heading: "Projets sélectionnés",
      intro:
        "RAG de production, serving on-premise et produit SaaS — les systèmes que j'ai réellement déployés.",
      items: [
        {
          id: "proj-ncore",
          title: "NCORE AI",
          subtitle: "HENSOLDT",
          year: "2026",
          featured: true,
          confidential: true,
          summary:
            "Système RAG de production pour identifier les codes NATO Item Name à partir de documentations techniques PDF — déployé on-premise sur NVIDIA DGX Spark, en air-gapped.",
          bullets: [
            "Retrieval hybride FAISS + BM25 + RRF, reranking BGE, Mistral-Small-4 via vLLM",
            "Ingestion PDF multimodale (vision) et garde-fou de traduction",
            "Évaluation : Hit@1 19 % → 31 %, ~22 s / document",
          ],
          metrics: [
            { label: "Hit@1", value: "19% → 31%" },
            { label: "Latence", value: "~22s / doc" },
          ],
          tags: [
            "RAG",
            "vLLM",
            "FAISS",
            "BGE",
            "Mistral",
            "NVIDIA DGX",
            "Air-gapped",
          ],
        },
        {
          id: "proj-nato-rag",
          title: "Recherche sémantique NATO",
          subtitle: "État-major des armées — CIMD",
          year: "2024 — 2026",
          featured: false,
          confidential: true,
          summary:
            "Moteur RAG et assistant IA pour la codification NATO et l'interrogation des règles métier, en environnement on-premise sécurisé.",
          bullets: [
            "Embeddings multilingual-e5-large + index FAISS",
            "Assistant Mistral + RAG pour les règles NATO",
            "Interfaces CLI + Streamlit et dashboards QlikSense",
          ],
          tags: ["RAG", "FAISS", "Mistral", "Streamlit", "QlikSense", "On-premise"],
        },
        {
          id: "proj-planquia",
          title: "Planquia",
          subtitle: "Conjectura — SaaS",
          year: "2026",
          featured: false,
          confidential: false,
          url: "https://planquia.com",
          summary:
            "SaaS IA qui transforme des plans PDF de construction en devis structurés. Pipeline multimodal OCR + vision + raisonnement LLM, du document brut à la quotation.",
          bullets: [
            "Extraction multimodale (OCR, computer vision, LLM)",
            "Backend FastAPI / SQLAlchemy, frontend React / Next.js",
            "PostgreSQL, architecture produit et roadmap",
          ],
          tags: ["SaaS", "OCR", "Vision", "LLM", "FastAPI", "Next.js", "PostgreSQL"],
        },
      ],
    },
    skills: {
      eyebrow: "// 04 — Stack",
      heading: "Compétences techniques",
      intro:
        "Une stack pensée pour le GenAI de production — y compris le serving local, air-gapped, sur hardware contraint.",
      languagesTitle: "Langues",
      languagesIntro: "Communication fluide en contexte international et défense.",
      groups: [
        {
          category: "On-premise & serving",
          icon: "Server",
          featured: true,
          items: [
            "vLLM",
            "Serving local / air-gapped",
            "NVIDIA DGX",
            "Optimisation GPU / unified memory",
            "CPU offloading",
            "Quantization NVFP4",
            "Profiling de latence",
          ],
        },
        {
          category: "GenAI & LLMs",
          icon: "Sparkles",
          featured: true,
          items: skillsShared.genai,
        },
        {
          category: "Langages & ML",
          icon: "BrainCircuit",
          items: skillsShared.ml,
        },
        {
          category: "Ingénierie & MLOps",
          icon: "Terminal",
          items: [
            "Pipelines ML end-to-end",
            "FastAPI",
            "REST API",
            "Docker",
            "Git",
            "CI/CD",
            "Tests unitaires",
            "Harness d'évaluation",
            "Clean Code",
            "Agile / Scrum",
          ],
        },
        {
          category: "Data & outils",
          icon: "Database",
          items: [
            "Streamlit",
            "Dataiku",
            "Spark",
            "MongoDB",
            "PostgreSQL",
            "QlikSense",
            "GCP / Azure (bases)",
          ],
        },
      ],
      spoken: [
        { name: "Français", level: "Langue maternelle", value: 100 },
        { name: "Swahili", level: "Bilingue", value: 95 },
        { name: "Anglais", level: "C1 — Courant", value: 88 },
        { name: "Arabe", level: "Professionnel", value: 70 },
      ],
    },
    education: {
      eyebrow: "// 05 — Académique",
      heading: "Formation",
      intro:
        "Cursus ingénieur en mathématiques appliquées, informatique et intelligence artificielle.",
      items: [
        {
          id: "edu-1",
          school: "CY Tech",
          degree: "Diplôme d'ingénieur — spécialisation IA",
          field: "Mathématiques appliquées & Informatique. Attendu en 2027.",
          period: "2023 — 2027",
        },
        {
          id: "edu-2",
          school: "ENSGSI",
          degree: "Cycle ingénieur",
          field: "Génie des systèmes industriels & innovation",
          period: "2021 — 2023",
        },
        {
          id: "edu-3",
          school: "CPGE TSI",
          degree: "Classes préparatoires",
          field: "Technologie & Sciences Industrielles",
          period: "2018 — 2021",
        },
      ],
    },
    planquia: {
      eyebrow: "// 06 — Produit",
      heading: "Planquia — le produit que je construis",
      intro:
        "Co-fondateur & CTO de Conjectura, je développe Planquia : un SaaS qui lit des plans de construction et en sort des devis structurés.",
      blurb:
        "Des plans PDF de construction aux devis structurés : Planquia automatise l'extraction, le raisonnement et la quotation pour les professionnels du BTP.",
      pillars: [
        {
          icon: "Layers",
          title: "Pipeline multimodal",
          text: "OCR, computer vision et raisonnement LLM pour extraire l'information utile de PDFs techniques souvent hétérogènes.",
        },
        {
          icon: "Zap",
          title: "Full-stack, prêt à scaler",
          text: "Python, FastAPI, SQLAlchemy, React / Next.js et PostgreSQL — de l'API au produit, avec une architecture claire.",
        },
        {
          icon: "ShieldCheck",
          title: "Ownership produit",
          text: "Architecture, backend, qualité de code et roadmap : je porte le système de l'idée jusqu'aux utilisateurs.",
        },
      ],
    },
    contact: {
      eyebrow: "// 07 — Entrons en contact",
      heading: "Discutons de votre projet",
      intro:
        "Un système RAG à industrialiser, un déploiement on-premise, une collaboration autour de Planquia — écrivez-moi, je lis chaque message.",
      email: "EMAIL",
      location: "LOCALISATION",
      name: "NOM",
      message: "MESSAGE",
      namePlaceholder: "Votre nom",
      emailPlaceholder: "vous@exemple.com",
      messagePlaceholder: "Parlez-moi de votre projet, contexte, besoin…",
      hint: "Réponse sous 24–48h — le message m'arrive directement par email.",
      send: "Envoyer le message",
      sending: "Envoi…",
      sentTitle: "Message bien envoyé",
      sentBody: "Merci. Je reviens vers vous sous 24–48h à l'adresse indiquée.",
      sendAnother: "Envoyer un autre message",
      missingTitle: "Champs manquants",
      missingBody: "Merci de remplir tous les champs avant d'envoyer.",
      successTitle: "Message envoyé",
      successBody: "Merci — je vous réponds sous 24–48h.",
      errorTitle: "Envoi impossible",
      errorBody:
        "Réessayez dans un instant, ou écrivez-moi directement par email.",
      subjectPrefix: "Portfolio — message de",
    },
  },
  en: {
    ui: {
      documentTitle: "Arkam ALI — AI/ML Engineer | GenAI, RAG, On-premise",
      contactMe: "Get in touch",
      seeProjects: "View projects",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      allRepos: "All repos",
      flagship: "Flagship",
      confidential: "Confidential",
      current: "Current",
      openProject: "Open",
      visitPlanquia: "Visit planquia.com",
      navLabel: "NAVIGATION",
      elsewhere: "ELSEWHERE",
      rights: "All rights reserved.",
      crafted: "Designed & built with care • Paris",
      langSwitch: "Language",
    },
    navLinks: [
      { href: "#about", label: "About" },
      { href: "#experience", label: "Experience" },
      { href: "#projects", label: "Projects" },
      { href: "#skills", label: "Skills" },
      { href: "#education", label: "Education" },
      { href: "#planquia", label: "Planquia" },
      { href: "#contact", label: "Contact" },
    ],
    personal: {
      title: "AI/ML Engineer — Production GenAI",
      tagline:
        "I design and ship production GenAI systems — RAG, semantic search, and LLM serving — including on-premise and air-gapped setups, with no cloud dependency.",
      location: "Paris, France",
      status: "HENSOLDT internship (Germany) • On-premise GenAI",
      companyRole: "Co-founder & CTO",
      chips: [
        "Production GenAI",
        "Hybrid RAG",
        "On-premise / air-gapped",
        "vLLM · FAISS",
      ],
      footerBlurb:
        "AI/ML engineer — production GenAI, RAG, and on-premise deployment. Based in Paris.",
    },
    about: {
      eyebrow: "// 01 — Profile",
      heading: "GenAI systems that hold up in production",
      paragraphs: [
        "As an AI/ML engineer, I build production GenAI systems — RAG, semantic search, and LLM serving — with end-to-end ownership: data prep, modeling, evaluation, and latency tuning.",
        "My distinctive ground: on-premise and air-gapped deployment, with no cloud dependency. I have designed and industrialised these stacks in defence settings — at HENSOLDT (Germany) and the French Armed Forces General Staff (CIMD) — on constrained infrastructure (vLLM, FAISS, NVIDIA DGX).",
        "In parallel I am co-founder & CTO of Conjectura. I am building Planquia, a SaaS that turns construction PDF plans into structured quotations through a multimodal pipeline (OCR, vision, LLM reasoning).",
      ],
      highlights: [
        { label: "NCORE AI Hit@1", value: "+12 pts" },
        { label: "Latency / document", value: "~22s" },
        { label: "Deployment", value: "Air-gapped" },
        { label: "Languages spoken", value: "4" },
      ],
    },
    experience: {
      eyebrow: "// 02 — Path",
      heading: "Professional experience",
      items: [
        {
          id: "exp-hensoldt",
          role: "Software Engineer — AI",
          kind: "International internship",
          company: "HENSOLDT",
          period: "June — Sept. 2026",
          location: "Fürstenfeldbruck, Germany",
          current: true,
          description:
            "Designed and deployed NCORE AI, an end-to-end RAG system for NATO Item Name Code identification from technical PDFs — in an air-gapped environment, with no cloud.",
          achievements: [
            "Deployed on NVIDIA DGX Spark with vLLM, tuned for constrained infrastructure (GPU / unified memory, CPU offloading, NVFP4 quantization).",
            "Hybrid retrieval pipeline: FAISS + BM25 + Reciprocal Rank Fusion, BGE cross-encoder reranking, Mistral-Small-4 generation.",
            "Multimodal vision-based PDF ingestion and a translation guard for a multilingual technical corpus.",
            "Evaluation harness: Hit@1 raised from 19% to 31%, latency brought down to ~22 s per document.",
          ],
          stack: [
            "vLLM",
            "FAISS",
            "BM25",
            "RRF",
            "BGE-Reranker",
            "Mistral-Small-4",
            "NVIDIA DGX",
            "Python",
          ],
        },
        {
          id: "exp-cimd",
          role: "Data Scientist / AI Engineer",
          kind: "Apprenticeship",
          company: "French Armed Forces General Staff — CIMD",
          period: "Sept. 2024 — Aug. 2026",
          location: "Paris",
          current: false,
          description:
            "Shipped a semantic search engine and an AI assistant for NATO codification, in a secure on-premise environment.",
          achievements: [
            "Semantic search engine (RAG) for NATO codification, multilingual-e5-large embeddings and FAISS vector indexing.",
            "AI assistant (Mistral + RAG) for querying NATO rules, with controlled context injection.",
            "Operational CLI + Streamlit interfaces for daily use.",
            "QlikSense dashboards and KPIs, inside a constrained on-premise information system.",
          ],
          stack: [
            "Python",
            "RAG",
            "FAISS",
            "Mistral",
            "multilingual-e5-large",
            "Streamlit",
            "QlikSense",
          ],
        },
        {
          id: "exp-conjectura",
          role: "Co-founder & CTO",
          kind: "Venture",
          company: "Conjectura — Planquia",
          period: "2026 — Present",
          location: "Paris",
          current: true,
          description:
            "Lead developer of Planquia, an AI SaaS that converts construction PDF plans into structured quotations. Architecture, backend, and product roadmap.",
          achievements: [
            "Multimodal AI pipeline: OCR, computer vision, and LLM reasoning to extract and structure information from plans.",
            "Full-stack: Python, FastAPI, SQLAlchemy, React / Next.js, PostgreSQL.",
            "Product ownership: architecture, API, code quality, and roadmap prioritisation.",
          ],
          stack: [
            "Python",
            "FastAPI",
            "SQLAlchemy",
            "Next.js",
            "PostgreSQL",
            "OCR",
            "LLM",
          ],
        },
      ],
    },
    projects: {
      eyebrow: "// 03 — Work",
      heading: "Selected projects",
      intro:
        "Production RAG, on-premise serving, and a SaaS product — systems I have actually shipped.",
      items: [
        {
          id: "proj-ncore",
          title: "NCORE AI",
          subtitle: "HENSOLDT",
          year: "2026",
          featured: true,
          confidential: true,
          summary:
            "Production RAG system to identify NATO Item Name Codes from technical PDF documentation — deployed on-premise on NVIDIA DGX Spark, air-gapped.",
          bullets: [
            "Hybrid retrieval FAISS + BM25 + RRF, BGE reranking, Mistral-Small-4 via vLLM",
            "Multimodal PDF ingestion (vision) and a translation guard",
            "Evaluation: Hit@1 19% → 31%, ~22 s / document",
          ],
          metrics: [
            { label: "Hit@1", value: "19% → 31%" },
            { label: "Latency", value: "~22s / doc" },
          ],
          tags: [
            "RAG",
            "vLLM",
            "FAISS",
            "BGE",
            "Mistral",
            "NVIDIA DGX",
            "Air-gapped",
          ],
        },
        {
          id: "proj-nato-rag",
          title: "NATO semantic search",
          subtitle: "French Armed Forces — CIMD",
          year: "2024 — 2026",
          featured: false,
          confidential: true,
          summary:
            "RAG engine and AI assistant for NATO codification and business-rule querying, in a secure on-premise environment.",
          bullets: [
            "multilingual-e5-large embeddings + FAISS index",
            "Mistral + RAG assistant for NATO rules",
            "CLI + Streamlit interfaces and QlikSense dashboards",
          ],
          tags: ["RAG", "FAISS", "Mistral", "Streamlit", "QlikSense", "On-premise"],
        },
        {
          id: "proj-planquia",
          title: "Planquia",
          subtitle: "Conjectura — SaaS",
          year: "2026",
          featured: false,
          confidential: false,
          url: "https://planquia.com",
          summary:
            "AI SaaS that turns construction PDF plans into structured quotations. Multimodal OCR + vision + LLM reasoning, from raw documents to quotes.",
          bullets: [
            "Multimodal extraction (OCR, computer vision, LLM)",
            "FastAPI / SQLAlchemy backend, React / Next.js frontend",
            "PostgreSQL, product architecture and roadmap",
          ],
          tags: ["SaaS", "OCR", "Vision", "LLM", "FastAPI", "Next.js", "PostgreSQL"],
        },
      ],
    },
    skills: {
      eyebrow: "// 04 — Stack",
      heading: "Technical skills",
      intro:
        "A stack built for production GenAI — including local, air-gapped serving on constrained hardware.",
      languagesTitle: "Languages",
      languagesIntro: "Fluent communication in international and defence settings.",
      groups: [
        {
          category: "On-premise & serving",
          icon: "Server",
          featured: true,
          items: [
            "vLLM",
            "Local / air-gapped serving",
            "NVIDIA DGX",
            "GPU / unified-memory optimisation",
            "CPU offloading",
            "NVFP4 quantization",
            "Latency profiling",
          ],
        },
        {
          category: "GenAI & LLMs",
          icon: "Sparkles",
          featured: true,
          items: skillsShared.genai,
        },
        {
          category: "Languages & ML",
          icon: "BrainCircuit",
          items: skillsShared.ml,
        },
        {
          category: "Engineering & MLOps",
          icon: "Terminal",
          items: [
            "End-to-end ML pipelines",
            "FastAPI",
            "REST API",
            "Docker",
            "Git",
            "CI/CD",
            "Unit testing",
            "Evaluation harnesses",
            "Clean Code",
            "Agile / Scrum",
          ],
        },
        {
          category: "Data & tools",
          icon: "Database",
          items: [
            "Streamlit",
            "Dataiku",
            "Spark",
            "MongoDB",
            "PostgreSQL",
            "QlikSense",
            "GCP / Azure (basics)",
          ],
        },
      ],
      spoken: [
        { name: "French", level: "Native", value: 100 },
        { name: "Swahili", level: "Bilingual", value: 95 },
        { name: "English", level: "C1 — Fluent", value: 88 },
        { name: "Arabic", level: "Professional", value: 70 },
      ],
    },
    education: {
      eyebrow: "// 05 — Academic",
      heading: "Education",
      intro:
        "Engineering track in applied mathematics, computer science, and artificial intelligence.",
      items: [
        {
          id: "edu-1",
          school: "CY Tech",
          degree: "Engineering degree — AI specialisation",
          field: "Applied mathematics & Computer science. Expected 2027.",
          period: "2023 — 2027",
        },
        {
          id: "edu-2",
          school: "ENSGSI",
          degree: "Engineering cycle",
          field: "Industrial systems engineering & innovation",
          period: "2021 — 2023",
        },
        {
          id: "edu-3",
          school: "CPGE TSI",
          degree: "Preparatory classes",
          field: "Technology & Industrial Sciences",
          period: "2018 — 2021",
        },
      ],
    },
    planquia: {
      eyebrow: "// 06 — Product",
      heading: "Planquia — the product I am building",
      intro:
        "As co-founder & CTO of Conjectura, I am building Planquia: a SaaS that reads construction plans and outputs structured quotations.",
      blurb:
        "From construction PDFs to structured quotes: Planquia automates extraction, reasoning, and quotation for building professionals.",
      pillars: [
        {
          icon: "Layers",
          title: "Multimodal pipeline",
          text: "OCR, computer vision, and LLM reasoning to extract useful information from often messy technical PDFs.",
        },
        {
          icon: "Zap",
          title: "Full-stack, ready to scale",
          text: "Python, FastAPI, SQLAlchemy, React / Next.js, and PostgreSQL — from the API to the product, with a clear architecture.",
        },
        {
          icon: "ShieldCheck",
          title: "Product ownership",
          text: "Architecture, backend, code quality, and roadmap: I take the system from idea to users.",
        },
      ],
    },
    contact: {
      eyebrow: "// 07 — Let's talk",
      heading: "Tell me about your project",
      intro:
        "A RAG system to industrialise, an on-premise rollout, a collaboration around Planquia — write to me, I read every message.",
      email: "EMAIL",
      location: "LOCATION",
      name: "NAME",
      message: "MESSAGE",
      namePlaceholder: "Your name",
      emailPlaceholder: "you@example.com",
      messagePlaceholder: "Tell me about your project, context, and needs…",
      hint: "Reply within 24–48h — the message lands in my inbox directly.",
      send: "Send message",
      sending: "Sending…",
      sentTitle: "Message sent",
      sentBody: "Thank you. I will get back to you within 24–48h at the address you gave.",
      sendAnother: "Send another message",
      missingTitle: "Missing fields",
      missingBody: "Please fill in every field before sending.",
      successTitle: "Message sent",
      successBody: "Thank you — I will reply within 24–48h.",
      errorTitle: "Could not send",
      errorBody: "Please try again in a moment, or email me directly.",
      subjectPrefix: "Portfolio — message from",
    },
  },
};
